### ISSUE TITLE
Bulk Purge cache not working

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#17]
This is exactly the same problem as in https://github.com/Rarst/sg-cachepress/issues/8 - the bulk purge cache is not working.

This is a problem on the subfolder installation only - https://sgmstest-subfolder.com/, but works properly on the subdomain one - sgmstest-subdomain.com and on the mapped domains installation - https://sgmstest-mapdomain.com.

**Comment by Rarst** [comment]
Cannot reproduce as of right now.

For sites on https://sgmstest-subfolder.com/ both bulk action purge and individual purge cache link cause subsequent request to be a cache MISS correctly (testing with Postman).

I've double checked generated PURGE request and it seems to be valid for subfolder case as well, e.g.

```
PURGE /sg-optimizer/(.*) HTTP/1.0
Host: multisite.test
Connection: Close
```

Could you please double check your results in this case?

**Comment by kojuharov** [comment]
I checked again with https://sgmstest-subfolder.com/kojuharov2/ and the problem persists. Enable Dynamic Cache, access the website until the HIT header shows. Then bulk disable Dynamic Cache and try again - still HIT. Try Bulk Purge - still HIT.

I created a brand new site - https://sgmstest-subfolder.com/kojuharov3/, and the problem is present there as well.

I am testing with cURL requests. With Dynamic Cache enabled:

`georgikojuharov@Georgi-Kojuharov:~$ curl -I -X GET https://sgmstest-subfolder.com/kojuharov3/
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 24 Aug 2017 11:42:07 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Cache-Enabled: True
Link: <https://sgmstest-subfolder.com/kojuharov3/wp-json/>; rel="https://api.w.org/"
Set-Cookie: wpSGCacheBypass=0; expires=Thu, 24-Aug-2017 10:37:33 GMT; Max-Age=0; path=/
Host-Header: 192fc2e7e50945beb8231a492d6a8024
X-Proxy-Cache: HIT`

After disabling it in bulk for all sites:

`georgikojuharov@Georgi-Kojuharov:~$ curl -I -X GET https://sgmstest-subfolder.com/kojuharov3/
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 24 Aug 2017 11:42:41 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Cache-Enabled: True
Link: <https://sgmstest-subfolder.com/kojuharov3/wp-json/>; rel="https://api.w.org/"
Set-Cookie: wpSGCacheBypass=0; expires=Thu, 24-Aug-2017 10:37:33 GMT; Max-Age=0; path=/
Host-Header: 192fc2e7e50945beb8231a492d6a8024
X-Proxy-Cache: HIT`

After Bulk Purge:

`georgikojuharov@Georgi-Kojuharov:~$ curl -I -X GET https://sgmstest-subfolder.com/kojuharov3/
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 24 Aug 2017 11:43:08 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Cache-Enabled: True
Link: <https://sgmstest-subfolder.com/kojuharov3/wp-json/>; rel="https://api.w.org/"
Set-Cookie: wpSGCacheBypass=0; expires=Thu, 24-Aug-2017 10:37:33 GMT; Max-Age=0; path=/
Host-Header: 192fc2e7e50945beb8231a492d6a8024
X-Proxy-Cache: HIT`

**Comment by Rarst** [comment]
Strange, this is right before and after cache purge for me:

```
c:\Software\curl>curl -I -X GET https://sgmstest-subfolder.com/kojuharov3/
HTTP/2 200
server: nginx
date: Thu, 24 Aug 2017 11:57:36 GMT
content-type: text/html; charset=UTF-8
x-cache-enabled: True
link: <https://sgmstest-subfolder.com/kojuharov3/wp-json/>; rel="https://api.w.org/"
set-cookie: wpSGCacheBypass=0; expires=Thu, 24-Aug-2017 10:54:37 GMT; Max-Age=0; path=/
host-header: 192fc2e7e50945beb8231a492d6a8024
x-proxy-cache: HIT

c:\Software\curl>curl -I -X GET https://sgmstest-subfolder.com/kojuharov3/
HTTP/2 200
server: nginx
date: Thu, 24 Aug 2017 11:57:55 GMT
content-type: text/html; charset=UTF-8
x-cache-enabled: True
link: <https://sgmstest-subfolder.com/kojuharov3/wp-json/>; rel="https://api.w.org/"
set-cookie: wpSGCacheBypass=0; expires=Thu, 24-Aug-2017 10:57:55 GMT; Max-Age=0; path=/
host-header: 192fc2e7e50945beb8231a492d6a8024
x-proxy-cache: MISS
```

**Comment by Rarst** [comment]
Might this be related to `Connection: keep-alive` ? I don't see it in my results.

**Comment by kojuharov** [comment]
Perhaps you are purging the cache only for this single website via the Purge Cache red button for it, which works properly.

If I purge the cache from https://sgmstest-subfolder.com/wp-admin/network/sites.php -> Mark all websites -> Purge Cache from the Bulk Actions drop down menu it does not work properly. The same goes for Disable Dynamic Cache.

As for the keep-alive, it does not appear to be the cause, since using -v in cURL shows that new connections are established each time:

> georgikojuharov@Georgi-Kojuharov:~$ curl -I -X GET -v https://sgmstest-subfolder.com/kojuharov3/
> *   Trying 109.73.233.82...
> * Connected to sgmstest-subfolder.com (109.73.233.82) port 443 (#0)
> * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> * Server certificate: sgmstest-subfolder.com
> * Server certificate: Let's Encrypt Authority X3
> * Server certificate: DST Root CA X3
> > GET /kojuharov3/ HTTP/1.1
> > Host: sgmstest-subfolder.com
> > User-Agent: curl/7.43.0
> > Accept: */*
> >
> < HTTP/1.1 200 OK
> HTTP/1.1 200 OK
> < Server: nginx
> Server: nginx
> < Date: Thu, 24 Aug 2017 12:14:03 GMT
> Date: Thu, 24 Aug 2017 12:14:03 GMT
> < Content-Type: text/html; charset=UTF-8
> Content-Type: text/html; charset=UTF-8
> < Transfer-Encoding: chunked
> Transfer-Encoding: chunked
> < Connection: keep-alive
> Connection: keep-alive
> < X-Cache-Enabled: True
> X-Cache-Enabled: True
> < Link: <https://sgmstest-subfolder.com/kojuharov3/wp-json/>; rel="https://api.w.org/"
> Link: <https://sgmstest-subfolder.com/kojuharov3/wp-json/>; rel="https://api.w.org/"
> < Set-Cookie: wpSGCacheBypass=0; expires=Thu, 24-Aug-2017 11:03:42 GMT; Max-Age=0; path=/
> Set-Cookie: wpSGCacheBypass=0; expires=Thu, 24-Aug-2017 11:03:42 GMT; Max-Age=0; path=/
> < Host-Header: 192fc2e7e50945beb8231a492d6a8024
> Host-Header: 192fc2e7e50945beb8231a492d6a8024
> < X-Proxy-Cache: HIT
> X-Proxy-Cache: HIT
> 
> <
> * Excess found in a non pipelined read: excess = 15956 url = /kojuharov3/ (zero-length body)
> * Connection #0 to host sgmstest-subfolder.com left intact

**Comment by Rarst** [comment]
> Perhaps you are purging the cache only for this single website via the Purge Cache red button for it, which works properly.

I've tried all three cases, cache seems to flush for me correctly for all.

Still, could you please try with `--no-keepalive` ? So far I don't have a better guess what might be the difference in results, given that we are testing same server.

**Comment by Rarst** [comment]
Think I got it, I have been using bulk action but only selecting specific site. Selecting _all_ sites does seem to have an issue, looking into.

**Comment by Rarst** [comment]
Ok, think I got it. The method that determines application path wasn't written to determine _different_ paths within same load and it was caching the _first_ path called and returned invalid result for the remainder of bulk run.

**Comment by kojuharov** [comment]
Nice, tested and it is working as intended now.
