### ISSUE TITLE
Hide inactive menus

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#19]
Currently, if you access the dashboard of a subsite, then go to SuperCacher, there is a menu **HTTPS config**. When the plugin is network activated, this menu should be hidden as the button in it does not work and the information in the menu page suggests that it should.

I am talking about this menu here:

https://screenshots.firefox.com/9QTsKLWdlIGplNlq/sgmstest-mapped.com

The actual Force HTTPS happens from the network admin menu, so the Force HTTPS menu should be hidden if the plugin is network activated.

**Comment by Rarst** [comment]
Per initial spec HTTPS settings are retained for multisite though #1 ?

We've just cut down on what settings _does_ for them, bugging out on touching htaccess.

**Comment by kojuharov** [comment]
Yes, the MU users should be able to use use the Force HTTPS functionality, but it is manageable from the Network Admin -> Sites -> Specific site Settings.

Currently however, if you go to the Dashboard of a site, part of a WPMU -> SuperCacher tool, there is a HTTPS menu. That menu should not be there at all as it does not work, the button there does nothing.

Basically the whole SuperCacher -> HTTPS menu should be hidden from the Dashboard of the individual websites if your website is a WPMU.

**Comment by Rarst** [comment]
Ok, that had been _explicitly_ covered by spec as something that _should_ be there.

> ### Regular admin
> ...
> If the HTTPS config is allowed
> - Show link in the left menu for the SG Optimizer with the submenu the HTTPS Config. Regular User should see the force HTTPS functionality.
>
> #1

I am just trying to figure out which is it: 

1. Original spec is correct and it _should_ be there?
2. I am misunderstanding original spec as written?
3. There has been a change on this since original spec?

**Comment by pandjarov** [comment]
The idea was to allow "end users" to manipulate it but since we decided on a later stage that that would break more functionality than we expected, it's better to remove it.

Simply hide the menu from the end users and let me know how to edit the plugin's index page to remove the link from there. This setting should be configured by the network admin only

**Comment by Rarst** [comment]
Ok, I guess then we should also drop network admin "Disallow HTTPS Configuration" option since it makes no sense anymore?

**Comment by pandjarov** [comment]
Discussed with Andrey to keep the functionality as we initially discussed. The HTTPS Config menu link should be shown only when the Disallow HTTPS configuration is unchecked.
