### ISSUE TITLE
Performance test tool roadmap

### ISSUE THREAD

**Issue by Rarst** [Rarst/sg-cachepress#2]
## Scope

Implement performance test tool screen to allow users benchmark performance of their site’s pages and compare with last test to determine effects of changes.

## Page design

![performance tool design](https://user-images.githubusercontent.com/737584/29261452-40c23c24-80d8-11e7-98d9-9f7f7001f2dd.jpg)

### Page list to test

UI for number of pages (max 10), pre–filled with suggested list:

- home page / blog posts archive
- static front page (if enabled)
- single post page (pick longest content?)
- single page page (pick longest content?)
- category archive (pick category with max posts?)
- tag archive (pick tag with max posts?)
- 404 page
- search result page (site name as search term?)

### Output

```
Current test: 11:26 2017-07-06					Previous test: 11:26 2017-06-06
Average Load Time: 3.2s						Average Load Time: 4.2s
Slowest Page: /about-me/ 5.8s					Slowest Page: /about-me/ 5.8s
Fastest Page: / 0.8s.							Fastest Page: / 1.8s.
------
Site Loading: 
0.5s WordPress Core
```
Add list of results for all URLs tested? Helpful to see significant differences between types.

### Performance recommendations

Under the results we need speed recommendations

 - Dynamic Caching On/Of - checks whether it’s turned on and shows message.
 - Latest PHP Version - checks whether you’re using the recommended PHP version
 - HTTP2 & SSL - checks whether HTTPS is forced on your site 
 - gZIP Compression - checks whether you content is gZIP-ed and if not - allows you to add rules to the .htaccess file with a button to enable it
 - Leverage Browser Caching - checks for rules in the .htaccess file and adds them with a button click if they are not present

### Differentiating between logged in users

Needs to be looked into, might be a little challenging to fake a logged in state.

:white_check_mark: focus on nginx cache layer.

### Per–plugin information

```
+ 5s Plugins
4s WooCommerce
0.5s JetPack
0.5s Yoast SEO
```
Unfortunately WP core load process does not allow to segment load performance data per plugin. See [#41346](https://core.trac.wordpress.org/ticket/41346).

### Asset load information

```
+ 2s Your Active Theme
1s /style.css
0.5s /js/stupid.js
0.5s /css/extra.css
```
This gets into nuance which _kind_ of performance we are measuring. From server point of view the initial target for performance improvement is _page generation time_.

Assets have no impact on page generation time. Capturing this information gets into realms of Real User Monitoring. This is challenging technically (requiring actual _browser_ context to test) and site owner performing this test themselves can seriously skew results from geographical implications.

I would recommend to omit this from initial scope.

## Needs decision :exclamation:

Technical implementation of requests, server– or client–side. I would stick with server for robustness and to minimize impact of network overhead.

:white_check_mark: Decided to go with server side.

## Pull requests

WIP :construction:

**Comment by pandjarov** [comment]
For the Logged /Non-logged we will change the logic.

The Default test will run "as is"

The advanced will have a "Disable Dynamic Cache" option (as if logged) which will practically pass a header to ensure that the Dynamic caching is skipped:

x-proxy-cache:SKIP

**Comment by pandjarov** [comment]
As for the requests, I would say whichever has lowest chance of hitting any server limit (apache timeout, php timeout, so on).
