### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#20]
The link in this sentence is incorrect:

> HTTP2 & SSL Enable SSL from the HTTPS Config page in order to start benefiting from the HTTP2 protocol improvements! 

The sentence can be seen in the Performance Test page, after you run the test on a website that opens via HTTP. The link points to http://WP_URL/wp-admin/page.php?page=ssl, while the proper URL is http://WP_URL/wp-admin/admin.php?page=ssl.

The difference is in the name of the script in the URL - page.php, it should be admin.php instead.

Currently, the link from that sentence results in a 404 Error.

The name of the script should be updated in views/performance-tool.php:

`                                    // translators: URL to the configuration page.
                                    __( 'Enable SSL from the <a href="%s">HTTPS Config page</a> in order to start benefiting from the HTTP2 protocol improvements!' ),
                                    add_query_arg( 'page', 'ssl', admin_url( 'page.php' ) )`

**Comment by kojuharov** [comment]
The same thing is present in the sentences for the Dynamic Cache and PHP Version. The URLs from the sentences are respectively:

https://sgmstest-subdomain.com/notmu/wp-admin/page.php?page=caching
https://sgmstest-subdomain.com/notmu/wp-admin/page.php?page=php-check

Should be admin.php, not page.php.

**Comment by Rarst** [comment]
Could you please check that you have the latest source on the site?

This should have been fixed in https://github.com/Rarst/sg-cachepress/commit/b032d8ddebcf8dd0628afc294975d9b37a5d37b0

**Comment by kojuharov** [comment]
Yes, you are correct and I apologize for that. I pulled the origin/feature-performance-tool branch, instead of the develop-features one, my mistake.

I can confirm that the problem is indeed resolved in the develop-features branch. Closing the bug.
