### ISSUE TITLE
No previous tests should show when using Analyze Site

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#22]
When using the button Analyze Site in the Performance Test section of the plugin you should only see one result. Currently you see the latest one, plus the one before it.

The functionality of having two results on the page at the same time is expected to appear only when you use the Repeat Test button.

Basically when you use Analyze Site, you should always see the results from the current test. When you use Repeat Test - the results form the current one and the one before it.

**Comment by Rarst** [comment]
The current logic uses matching settings. That is if you click "Analyze Site" and the settings (such as URLs) stay exactly the same then previous result is shown. If setting change then previous result is not shown.

**Comment by pandjarov** [comment]
Great. Leave it that way.
