### ISSUE TITLE
Performance test page fails on PHP 7.2 RC2

### ISSUE THREAD

**Issue by Rarst** [Rarst/sg-cachepress#24]
Possibly related error messages about `create_function()` deprecation.

**Comment by kojuharov** [comment]
Let's leave it like this for now. Until the latest RC version comes out there is no point in debugging this.

**Comment by Rarst** [comment]
To capture info:

1. There seems to be silent crash somewhere within `WP_Query` under unclear circumstances.
2. I talked about this in WP core slack and there hadn't been other reports, neither folks there were able to reproduce with PHP 7.2 RC2
