### ISSUE TITLE
PHP Compatibility check not working

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#27]
When you are using a PHP version below PHP 7.0 - PHP 5.6, 5.5, 5.4; the PHP Compatibility check page is not working - https://sgmstest-subdomain.com/notmu3/wp-admin/admin.php?page=php-check.

Here is a screenshot - https://screenshots.firefox.com/SYCTES59wRQ2wBfv/sgmstest-subdomain.com.

When you change the PHP version to PHP 7.0 and above the page works.

**Comment by Rarst** [comment]
Does it work in stable plugin release?.. On top of my head this isn't something I touched.

**Comment by kojuharov** [comment]
Yes, it works with the stable version of the plugin - https://screenshots.firefox.com/kMd85QNN8kDVeLAR/sgmstest-subdomain.com.

If I recall correctly this used to work on Monday before we started messing with the Performance page and the problems there.

**Comment by Rarst** [comment]
I cannot reproduce on `/notmu` site I am messing with. Bumped PHP down to 5.6.31, PHP Config screen loads correctly and compat check completes successfully:

![notmu-php-check](https://user-images.githubusercontent.com/737584/30960140-c9047904-a44a-11e7-814d-d0f405797eb9.png)

**Comment by kojuharov** [comment]
Ignore this problem for now since it does not appear to be related to the MU and Performance code you are working on.
