### ISSUE TITLE
Enable Cache/Autoflush options not working

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#28]
On a WPMU, when you go to Network Admin -> Sites -> pick a site -> Edit button -> Settings tab -> Enable Cache and Autoflush checkboxes are not working as intended.

You cannot make both options to be disabled at the same time. For example if the **Enable Cache** is enabled and **Autoflush** is disabled, you cannot disable **Enable Cache** as well. You however disable **Enable Cache** and enable **Autoflush** and the changes will be saved.

Same is present when **Enable Cache** is disabled and **Autoflush** is disabled. You cannot disable **Autoflush** without enabling **Enable Cache** first.

Both options should not be related to each other and you should be able to disable and enable each one of them individually. Enabling and disabling them individually works however when you are in the dashboard of the particular network website.

You can test with https://sgmstest-subfolder.com/wp-admin/network/site-settings.php?id=6. Currently it has **Enable Cache** enabled. Try and disable it from the URL above and you will see that nothing happens. If you enable **Autoflush** and disable **Enable Cache** it will work however.

The issue is present on all PHP versions.

**Comment by Rarst** [comment]
Ah, the problem wasn't settings depending on _each other_, but trying to disable _everything at once_. I got a little too smart with data checks there and code was thinking it got nothing to do in such case.

Fix pushed.

**Comment by kojuharov** [comment]
Fix resolved the problem. Closing the bug.
