### ISSUE TITLE
Disabling Enable Cache option not purging cache

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#29]
When you disable the **Enable Cache** option from WMPU Network Admin -> pick a site and click Edit -> Settings, the cache is not flushed and the site is still showing HIT.

This is similar to what was present in this bug - https://github.com/Rarst/sg-cachepress/issues/6.

The expected result is to flush the cache when the option is disabled.

**Comment by Rarst** [comment]
Fix pushed, just added a flush there.

I think I got the problems with flushing correct site worked out in #6 so it should work, let me know if not. :)

**Comment by kojuharov** [comment]
Tested and it is indeed fixed now, thanks.
