### ISSUE TITLE
Performance page pie chart incorrect info

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#34]
If you run an Advanced test as a logged user the pie chart shows 100% Other, which should not be the case.

Tested with different PHP versions, with and without Dynamic Cache enabled and the result is the same - the chart shows 100% Other - https://screenshots.firefox.com/hPT5X24lkZFPpeUV/sgmstest-subdomain.com.

**Comment by Rarst** [comment]
I suspect this is caused by the currently broken front-end of that site:

> The theme directory "twentyseventeen" does not exist.
> ERROR: The themes directory is either empty or doesn’t exist. Please check your installation.
>
> https://sgmstest-subdomain.com/notmu/

Could you please resolve the issue with the installation and try again?

**Comment by kojuharov** [comment]
Yeah, you were right. Indeed the problem is fixed when the theme is reinstalled.

Closing this one.
