### ISSUE TITLE
New Site options not working

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#37]
The New Site pair of options here - https://sgmstest-subdomain.com/wp-admin/network/admin.php?page=sg-cachepress are not working.

You can click the buttons to disable the two options, then refresh the page and they will turn back on automatically.

This is valid for both the Dynamic Cache and the Autoflush Cache options.

**Comment by Rarst** [comment]
Can't reproduce locally, toggles save and retain their state correctly for me.

Please verify that you have the most current code on site? There had been a recent fix to these, after security changes broke them, in https://github.com/SiteGround/sg-cachepress/commit/662489eaf022f3a31f823bdb60663a408f511a05

**Comment by kojuharov** [comment]
There is some change you made in the views/network-settings.php file which resolved the issue, since when you updated 30 minutes ago the problem was still there and:

> sgmstest@am15 [~/public_html/wp-content/plugins/sg-cachepress]# git pull https://github.com/Rarst/sg-cachepress.git master
From https://github.com/Rarst/sg-cachepress
branch            master     -> FETCH_HEAD
Already up-to-date.

I tried again now and there was a small change in the network-settings.php file:

> sgmstest@am15 [~/public_html/wp-content/plugins/sg-cachepress]# git pull https://github.com/Rarst/sg-cachepress.git master
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/Rarst/sg-cachepress
branch            master     -> FETCH_HEAD
Updating 78026c4..554bde2
Fast-forward
 views/network-settings.php | 2 ++
 1 file changed, 2 insertions(+)

and the problem is resolved now.

**Comment by Rarst** [comment]
Ah, that might have been because the fix was directly merged into _upstream_ master and _my_ repo master might not have been up to date. Sorry about the confusion. :)
