### ISSUE TITLE
Potential problem with class-sg-cachepress-multisite.php

### ISSUE THREAD

**Issue by sven4o** [Rarst/sg-cachepress#39]
Hello,

My name is Svetoslav and I am a colleagues of Georgi Kojuharov and Hristo Pandjarov at SiteGround.com.
 
A customer has reported the following error after the update of sg-cachepress to 4.0.6:

Notice: Undefined index: REQUEST_SCHEME in /home/$user/public_html/wp-content/plugins/sg-cachepress/class-sg-cachepress-multisite.php on line 90

I have found the following code on that line:

$scheme = $_SERVER['REQUEST_SCHEME'];

It is a part of the force_https() function.

If I use the following function:

print_r($_SERVER);

I see that there is no record for $_SERVER['REQUEST_SCHEME'];

Probably we should add code to check whether $_SERVER['REQUEST_SCHEME']; is defined.

For example we can use:

` if ( (! empty($_SERVER['REQUEST_SCHEME']) && $_SERVER['REQUEST_SCHEME'] == 'https') || (! empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') || (! empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == '443') ) {
            $scheme = 'https';
        } else {
            $scheme = 'http';
        }` 

or isset().

Could you please check the issue. 

We are looking forward to your opinion and a possible solution.

Best Regards,
Svetoslav

**Comment by Rarst** [comment]
Hm hm, if SG server environment doesn't have this then indeed needs to be detected in a different way. I'll work on a PR with adjustments.

To be clear do you want your example incorporated or what would be the exact reliable way to detect SSL use in SG server environment?

**Comment by sven4o** [comment]
Hello,
I have tested the code shared above and it will work on our environment. You can implement it in the solution.

**Comment by Rarst** [comment]
I've changed the code to `is_ssl()` check from core, it wraps checks for server properties you had pointed out. See the pull request. :)
