### ISSUE TITLE
Cache not Purged on Bulk Disable Cache

### ISSUE THREAD

**Issue by pandjarov** [Rarst/sg-cachepress#6]
When you disable the Dynamic Cache in Bulk, you need to purge the cache. Otherwise the sit remains cached until you purge it manually and THEN stops caching.

**Comment by Rarst** [comment]
I believe you also mentioned that purge method needs to be adjusted to purge specific site rather than whole domain.

It seems like this is related, since just calling purge method won't properly clear?

Could you please elaborate a bit how should purge implementation be enhanced to work correctly with caching layer in multisite environment?

**Comment by pandjarov** [comment]
In class-sg-cachepress-supercacher.php

we first check if you're on a Varnish or NGINX environment. That was for legacy purpose but now it's safe to remove that check since we don't have Varnish systems anymore.

Check the public static function purge_cache. 

That's the line purging the cache:

$request .= "Host: {$realhost}\r\n";

We've done some tweaking of that because we define the realhost variable parsing get_home_url if $_SERVER['SERVER_ADDR'] is not available. That happens when you're calling it from WP-CLI. 

I guess that would be the first strange thing you will notice.

The ban PURGE request itself happens here:

$purge_request = $sg_cachepress_supercacher->environment->get_application_path() . '(.*)';

as you can see that would delete the entire domain. We need to replace environment->get_application_path() . '(.*)'; with something more accurate.

**Comment by Rarst** [comment]
Ok, sanity check, is this what purge requests should look like?

Main site:
```
PURGE /(.*) HTTP/1.0
Host: multisite.test
Connection: Close
```

Subfolder multisite:
```
PURGE /sg-optimizer/(.*) HTTP/1.0
Host: multisite.test
Connection: Close
```

Mapped domain multisite:
```
PURGE /(.*) HTTP/1.0
Host: multisite-mapped.test
Connection: Close
```

**Comment by pandjarov** [comment]
Correct. Subdomain variation is equal to the mapped domain but make sure you pass the dubdomain, not the main one.

**Comment by pandjarov** [comment]
Tested, fixed.
