### ISSUE TITLE
Bulk Purge cache not working

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#8]
The bulk Purge Cache option is not working on subdomain and mapped setup. Works only with subfolder one.

Not working on: kojuharov2.sgmstest-subdomain.com and sgmstest-mapped.com
Working on: sgmstest-subfolder.com/testing-monday

**Comment by Rarst** [comment]
Likely same as / related to #7

**Comment by Rarst** [comment]
I strongly suspect this should be fixed by https://github.com/Rarst/sg-cachepress/commit/5264a9ef8f44351f016f18b9402225cef5c54602

**Comment by pandjarov** [comment]
Tested, fixed.
